using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace Helios.App.Services;

public static class LocalizationService
{
	private static readonly string SystemCultureCode = CultureInfo.CurrentUICulture.Name;

	private static readonly Dictionary<string, string> En = new(StringComparer.OrdinalIgnoreCase)
	{
		["AppName"] = "Helios - Sunshine Multi-Instance Manager",
		["Settings"] = "Settings",
		["OpenSettings"] = "Settings",
		["ThemeQuickSwitch"] = "Theme",
		["ThemeLight"] = "Light",
		["ThemeDark"] = "Dark",
		["TrayShowMain"] = "Show Main Window",
		["TrayInstances"] = "Instances",
		["TrayRestart"] = "Restart Manager",
		["TrayExit"] = "Exit",
		["TrayEnabled"] = "Enabled",
		["TrayDisabled"] = "Disabled",
		["StatusInstanceEnabled"] = "Instance enabled.",
		["StatusInstanceDisabled"] = "Instance disabled.",
		["Language"] = "Language",
		["ProductBranch"] = "Product Branch",
		["ProductBranchHint"] = "Choose which branch to install/update",
		["ProductTargetFolder"] = "Target Folder",
		["ProductTargetFolderHint"] = "Install folder used for this branch",
		["InstallerPathWarningTitle"] = "Install Path Notice",
		["InstallerPathWarningMessageFmt"] = "This installer will open in interactive mode.\n\nTo avoid conflicts, do not install into the same folder used by Sunshine/Apollo.\nPlease manually set a separate install path, for example:\n{0}",
		["InstallerStarted"] = "Installer launched. Follow the wizard to complete installation...",
		["InstallerStartedManualPathFmt"] = "Installer launched. This installer does not support auto path override; please manually set: {0}",
		["LanguageHint"] = "Takes effect immediately",
		["GroupVibeshine"] = "Sunshine",
		["GroupAutoStart"] = "Autostart",
		["GroupVolume"] = "Volume Sync",
		["GroupDisplay"] = "Display",
		["GroupService"] = "Service",
		["GroupBasic"] = "Basic",
		["GroupAudio"] = "Audio",
		["GroupAdvanced"] = "Advanced",
		["StatusBusy"] = "Working...",
		["CheckUpdate"] = "Check for Updates",
		["DownloadInstall"] = "Download and Install",
		["DownloadUpdate"] = "Download and Update",
		["Refresh"] = "Refresh",
		["DisableService"] = "Disable Service",
		["ServiceNotInstalled"] = "Service not installed",
		["AutoStartTitle"] = "Autostart",
		["AutoStartDesc"] = "Start tray app at sign-in (service still starts at boot)",
		["VolumeTitle"] = "Sync system volume",
		["VolumeDesc"] = "Sync default output volume to instances",
		["DisplayRestartTitle"] = "Restart instances when display changes",
		["DisplayRestartDesc"] = "Handle monitor topology/resolution changes",
		["DisplayRemoveTitle"] = "Remove virtual display on disconnect",
		["DisplayRemoveDesc"] = "Remove virtual display when client disconnects",
		["VibeshineDesc"] = "Manage Sunshine installation and updates",
		["InstalledLabel"] = "Installed",
		["NotInstalled"] = "Not installed",
		["BetaHint"] = "Include prerelease versions when checking updates",
		["AutoStartInfo"] = "Use Task Scheduler to start tray app at user sign-in; manager service still starts at boot",
		["VolumeInfo"] = "Syncs system volume changes",
		["ServiceInfo"] = "Sunshine installs SunshineService by default (auto-start as SYSTEM). Running both the service and manager-managed instances can conflict. It is recommended to disable SunshineService before first use.",
		["ServiceReminderHint"] = "Reminder only: disable both SunshineService and ApolloService to avoid conflicts with manager-controlled instances.",
		["ServiceCardName"] = "Sunshine Service",
		["IncludeBeta"] = "Include prerelease",
		["UpdateNoRelease"] = "No release information",
		["UpdateNotInstalledFmt"] = "Not installed, latest: {0}",
		["UpdateAvailableFmt"] = "Update available: {0} (installed: {1})",
		["UpdateLatestFmt"] = "Up to date: {0}",
		["ServiceStatusNotInstalled"] = "Not installed",
		["ServiceStatusRunning"] = "Running",
		["ServiceStatusStopped"] = "Stopped",
		["ServiceStatusStarting"] = "Starting",
		["ServiceStatusStopping"] = "Stopping",
		["ServiceStatusUnknown"] = "Unknown",
		["ServiceStartAuto"] = "(Auto)",
		["ServiceStartManual"] = "(Manual)",
		["ServiceStartDisabled"] = "(Disabled)",
		["ListAdd"] = "Add",
		["ListClone"] = "Clone",
		["ListDelete"] = "Delete",
		["TipAdd"] = "Add instance",
		["TipClone"] = "Clone instance",
		["TipDelete"] = "Delete instance",
		["EditorSelectPrompt"] = "Select an instance",
		["EditorApply"] = "Apply",
		["EditorDiscard"] = "Discard",
		["EditorStart"] = "Start",
		["EditorStop"] = "Stop",
		["EditorOpenWebUi"] = "Open Web UI",
		["StartAll"] = "Start All",
		["StopAll"] = "Stop All",
		["EditorEnable"] = "Enable instance",
		["EditorEnableHint"] = "Disabled instances will not start",
		["EditorInstanceName"] = "Instance name",
		["EditorInstanceNamePlaceholder"] = "Enter a name",
		["EditorPort"] = "Port",
		["EditorPortPlaceholder"] = "48100",
		["EditorBranch"] = "Branch",
		["EditorBranchHint"] = "Choose product branch for this instance",
		["EditorAudioDesc"] = "Select an audio output device for this instance",
		["EditorRefreshDevices"] = "Refresh devices",
		["EditorHeadlessTitle"] = "Headless mode",
		["EditorHeadlessDesc"] = "Run without creating virtual display output",
		["EditorTerminateTitle"] = "Terminate on pause",
		["EditorTerminateDesc"] = "Stop process when streaming is paused",
		["EditorExtraArgs"] = "Extra arguments",
		["EditorExtraArgsPlaceholder"] = "Optional command line arguments",
		["EditorExePath"] = "Executable path",
		["EditorBrowse"] = "Browse",
		["RunStatusRunning"] = "Running",
		["RunStatusStopped"] = "Stopped",
		["AudioAutoSelect"] = "Auto select",
		["StatusInstanceAdded"] = "Instance added",
		["StatusInstanceCloned"] = "Instance cloned",
		["StatusInstanceDeleted"] = "Instance deleted",
		["StatusChangesApplied"] = "Changes applied",
		["StatusChangesDiscarded"] = "Changes discarded",
		["StatusInstanceStarted"] = "Instance started",
		["StatusInstanceStopped"] = "Instance stopped",
		["StatusOpenWebUiRequested"] = "Open Web UI requested",
		["StatusThemeChangedFmt"] = "Theme switched to: {0}",
		["StatusAllInstancesStarted"] = "All instances started",
		["StatusAllInstancesStopped"] = "All instances stopped"
	};

	private static readonly Dictionary<string, string> ZhTw = new(StringComparer.OrdinalIgnoreCase)
	{
		["AppName"] = "Helios - Sunshine 多實例管理器",
		["ThemeQuickSwitch"] = "主題",
		["ThemeLight"] = "淺色",
		["ThemeDark"] = "深色",
		["Settings"] = "設定",
		["OpenSettings"] = "設定",
		["TrayShowMain"] = "顯示主視窗",
		["TrayInstances"] = "實例",
		["TrayRestart"] = "重新啟動管理器",
		["TrayExit"] = "結束",
		["TrayEnabled"] = "已啟用",
		["TrayDisabled"] = "已停用",
		["StatusInstanceEnabled"] = "實例已啟用。",
		["StatusInstanceDisabled"] = "實例已停用。",
		["Language"] = "語言",
		["ProductBranch"] = "產品分支",
		["ProductBranchHint"] = "選擇要安裝/更新的分支",
		["ProductTargetFolder"] = "目標資料夾",
		["ProductTargetFolderHint"] = "此分支使用的安裝資料夾",
		["InstallerPathWarningTitle"] = "安裝路徑提醒",
		["InstallerPathWarningMessageFmt"] = "此安裝器將以互動式精靈開啟。\n\n為避免衝突，請勿與 Sunshine/Apollo 使用相同安裝路徑。\n請手動改為獨立資料夾，例如：\n{0}",
		["InstallerStarted"] = "安裝程式已啟動，請依畫面指示完成安裝…",
		["InstallerStartedManualPathFmt"] = "安裝程式已啟動（此安裝器不支援自動帶入路徑，請手動改為：{0}）",
		["LanguageHint"] = "立即生效",
		["GroupVibeshine"] = "Sunshine",
		["GroupAutoStart"] = "自動啟動",
		["GroupVolume"] = "音量同步",
		["GroupDisplay"] = "顯示",
		["GroupService"] = "服務",
		["GroupBasic"] = "基本",
		["GroupAudio"] = "音訊",
		["GroupAdvanced"] = "進階",
		["StatusBusy"] = "處理中...",
		["CheckUpdate"] = "檢查更新",
		["DownloadInstall"] = "下載並安裝",
		["DownloadUpdate"] = "下載並更新",
		["Refresh"] = "重新整理",
		["DisableService"] = "停用服務",
		["ServiceNotInstalled"] = "服務尚未安裝",
		["AutoStartTitle"] = "自動啟動",
		["AutoStartDesc"] = "Windows 登入後自動啟動系統匣應用（服務仍於開機時啟動）",
		["VolumeTitle"] = "同步系統音量",
		["VolumeDesc"] = "將預設輸出音量同步到實例",
		["DisplayRestartTitle"] = "顯示變更時重啟實例",
		["DisplayRestartDesc"] = "處理螢幕拓樸與解析度變更",
		["DisplayRemoveTitle"] = "斷線時移除虛擬顯示器",
		["DisplayRemoveDesc"] = "用戶端中斷連線時移除虛擬顯示器",
		["VibeshineDesc"] = "管理 Sunshine 的安裝與更新",
		["InstalledLabel"] = "已安裝",
		["NotInstalled"] = "未安裝",
		["BetaHint"] = "檢查更新時包含預覽版本",
		["AutoStartInfo"] = "使用工作排程器於使用者登入後啟動系統匣應用；管理服務仍於開機時啟動",
		["VolumeInfo"] = "同步系統音量變更",
		["ServiceInfo"] = "Sunshine 預設會安裝 SunshineService（以 SYSTEM 權限自動啟動）。若同時啟用該服務與本管理器的多實例，可能發生衝突。建議首次使用前先停用 SunshineService。",
		["ServiceReminderHint"] = "此區僅提醒用途：建議停用 SunshineService 與 ApolloService，避免與管理器控制的實例衝突。",
		["ServiceCardName"] = "Sunshine 服務",
		["IncludeBeta"] = "包含測試版",
		["UpdateNoRelease"] = "目前沒有可用的發行資訊",
		["UpdateNotInstalledFmt"] = "尚未安裝，最新版本：{0}",
		["UpdateAvailableFmt"] = "可更新版本：{0}（已安裝：{1}）",
		["UpdateLatestFmt"] = "已是最新版本：{0}",
		["ServiceStatusNotInstalled"] = "未安裝",
		["ServiceStatusRunning"] = "執行中",
		["ServiceStatusStopped"] = "已停止",
		["ServiceStatusStarting"] = "啟動中",
		["ServiceStatusStopping"] = "停止中",
		["ServiceStatusUnknown"] = "未知",
		["ServiceStartAuto"] = "（自動）",
		["ServiceStartManual"] = "（手動）",
		["ServiceStartDisabled"] = "（停用）",
		["ListAdd"] = "新增",
		["ListClone"] = "複製",
		["ListDelete"] = "刪除",
		["TipAdd"] = "新增實例",
		["TipClone"] = "複製實例",
		["TipDelete"] = "刪除實例",
		["EditorSelectPrompt"] = "請先選擇一個實例",
		["EditorApply"] = "套用",
		["EditorDiscard"] = "捨棄",
		["EditorStart"] = "啟動",
		["EditorStop"] = "停止",
		["EditorOpenWebUi"] = "開啟 Web UI",
		["StartAll"] = "全部啟動",
		["StopAll"] = "全部停止",
		["EditorEnable"] = "啟用實例",
		["EditorEnableHint"] = "停用後將不會啟動",
		["EditorInstanceName"] = "實例名稱",
		["EditorInstanceNamePlaceholder"] = "輸入名稱",
		["EditorPort"] = "連接埠",
		["EditorPortPlaceholder"] = "48100",
		["EditorBranch"] = "分支",
		["EditorBranchHint"] = "為此實例選擇要使用的產品分支",
		["EditorAudioDesc"] = "選擇此實例的音訊輸出裝置",
		["EditorRefreshDevices"] = "重新整理裝置",
		["EditorHeadlessTitle"] = "無頭模式",
		["EditorHeadlessDesc"] = "不建立虛擬顯示輸出",
		["EditorTerminateTitle"] = "暫停時結束",
		["EditorTerminateDesc"] = "串流暫停時停止程序",
		["EditorExtraArgs"] = "額外參數",
		["EditorExtraArgsPlaceholder"] = "可選的命令列參數",
		["EditorExePath"] = "執行檔路徑",
		["EditorBrowse"] = "瀏覽",
		["RunStatusRunning"] = "執行中",
		["RunStatusStopped"] = "已停止",
		["AudioAutoSelect"] = "自動選擇",
		["StatusInstanceAdded"] = "已新增實例",
		["StatusInstanceCloned"] = "已複製實例",
		["StatusInstanceDeleted"] = "已刪除實例",
		["StatusChangesApplied"] = "變更已套用",
		["StatusChangesDiscarded"] = "已捨棄變更",
		["StatusInstanceStarted"] = "實例已啟動",
		["StatusInstanceStopped"] = "實例已停止",
		["StatusOpenWebUiRequested"] = "已要求開啟 Web UI",
		["StatusThemeChangedFmt"] = "主題已切換為：{0}",
		["StatusAllInstancesStarted"] = "全部實例已啟動",
		["StatusAllInstancesStopped"] = "全部實例已停止"
	};

	private static readonly Dictionary<string, string> ZhCn = new(StringComparer.OrdinalIgnoreCase)
	{
		["AppName"] = "Helios - Sunshine 多实例管理器",
		["ThemeQuickSwitch"] = "主题",
		["ThemeLight"] = "浅色",
		["ThemeDark"] = "深色",
		["Settings"] = "设置",
		["OpenSettings"] = "设置",
		["TrayShowMain"] = "显示主窗口",
		["TrayInstances"] = "实例",
		["TrayRestart"] = "重启管理器",
		["TrayExit"] = "退出",
		["TrayEnabled"] = "已启用",
		["TrayDisabled"] = "已禁用",
		["StatusInstanceEnabled"] = "实例已启用。",
		["StatusInstanceDisabled"] = "实例已禁用。",
		["Language"] = "语言",
		["ProductBranch"] = "产品分支",
		["ProductBranchHint"] = "选择要安装/更新的分支",
		["ProductTargetFolder"] = "目标文件夹",
		["ProductTargetFolderHint"] = "该分支使用的安装文件夹",
		["InstallerPathWarningTitle"] = "安装路径提醒",
		["InstallerPathWarningMessageFmt"] = "此安装器将以交互式向导启动。\n\n为避免冲突，请勿与 Sunshine/Apollo 使用相同安装路径。\n请手动改为独立目录，例如：\n{0}",
		["InstallerStarted"] = "安装程序已启动，请按向导完成安装…",
		["InstallerStartedManualPathFmt"] = "安装程序已启动（此安装器不支持自动带入路径，请手动改为：{0}）",
		["LanguageHint"] = "立即生效",
		["GroupVibeshine"] = "Sunshine",
		["GroupAutoStart"] = "自动启动",
		["GroupVolume"] = "音量同步",
		["GroupDisplay"] = "显示",
		["GroupService"] = "服务",
		["GroupBasic"] = "基础",
		["GroupAudio"] = "音频",
		["GroupAdvanced"] = "高级",
		["StatusBusy"] = "处理中...",
		["CheckUpdate"] = "检查更新",
		["DownloadInstall"] = "下载并安装",
		["DownloadUpdate"] = "下载并更新",
		["Refresh"] = "刷新",
		["DisableService"] = "禁用服务",
		["ServiceNotInstalled"] = "服务未安装",
		["AutoStartTitle"] = "自动启动",
		["AutoStartDesc"] = "Windows 登录后自动启动系统托盘应用（服务仍在开机时启动）",
		["VolumeTitle"] = "同步系统音量",
		["VolumeDesc"] = "将默认输出音量同步到实例",
		["DisplayRestartTitle"] = "显示变更时重启实例",
		["DisplayRestartDesc"] = "处理显示器拓扑和分辨率变化",
		["DisplayRemoveTitle"] = "断开连接时移除虚拟显示器",
		["DisplayRemoveDesc"] = "客户端断开时移除虚拟显示器",
		["VibeshineDesc"] = "管理 Sunshine 安装与更新",
		["InstalledLabel"] = "已安装",
		["NotInstalled"] = "未安装",
		["BetaHint"] = "检查更新时包含预发布版本",
		["AutoStartInfo"] = "使用任务计划程序在用户登录后启动托盘应用；管理服务仍在开机时启动",
		["VolumeInfo"] = "同步系统音量变化",
		["ServiceInfo"] = "Sunshine 默认会安装 SunshineService（以 SYSTEM 权限自动启动）。若同时启用该服务与本管理器的多实例，可能发生冲突。建议首次使用前先禁用 SunshineService。",
		["ServiceReminderHint"] = "此区仅用于提醒：建议禁用 SunshineService 与 ApolloService，避免与管理器控制的实例冲突。",
		["ServiceCardName"] = "Sunshine 服务",
		["IncludeBeta"] = "包含预发布版本",
		["UpdateNoRelease"] = "没有可用版本信息",
		["UpdateNotInstalledFmt"] = "未安装，最新版本：{0}",
		["UpdateAvailableFmt"] = "有可用更新：{0}（已安装：{1}）",
		["UpdateLatestFmt"] = "已是最新版本：{0}",
		["ServiceStatusNotInstalled"] = "未安装",
		["ServiceStatusRunning"] = "运行中",
		["ServiceStatusStopped"] = "已停止",
		["ServiceStatusStarting"] = "启动中",
		["ServiceStatusStopping"] = "停止中",
		["ServiceStatusUnknown"] = "未知",
		["ServiceStartAuto"] = "（自动）",
		["ServiceStartManual"] = "（手动）",
		["ServiceStartDisabled"] = "（禁用）",
		["ListAdd"] = "新增",
		["ListClone"] = "克隆",
		["ListDelete"] = "删除",
		["TipAdd"] = "新增实例",
		["TipClone"] = "克隆实例",
		["TipDelete"] = "删除实例",
		["EditorSelectPrompt"] = "请先选择一个实例",
		["EditorApply"] = "应用",
		["EditorDiscard"] = "放弃",
		["EditorStart"] = "启动",
		["EditorStop"] = "停止",
		["EditorOpenWebUi"] = "打开 Web UI",
		["StartAll"] = "全部启动",
		["StopAll"] = "全部停止",
		["EditorEnable"] = "启用实例",
		["EditorEnableHint"] = "禁用后该实例不会启动",
		["EditorInstanceName"] = "实例名称",
		["EditorInstanceNamePlaceholder"] = "输入名称",
		["EditorPort"] = "端口",
		["EditorPortPlaceholder"] = "48100",
		["EditorBranch"] = "分支",
		["EditorBranchHint"] = "为此实例选择要使用的产品分支",
		["EditorAudioDesc"] = "为此实例选择音频输出设备",
		["EditorRefreshDevices"] = "刷新设备",
		["EditorHeadlessTitle"] = "无头模式",
		["EditorHeadlessDesc"] = "运行时不创建虚拟显示输出",
		["EditorTerminateTitle"] = "暂停时终止",
		["EditorTerminateDesc"] = "串流暂停时停止进程",
		["EditorExtraArgs"] = "额外参数",
		["EditorExtraArgsPlaceholder"] = "可选命令行参数",
		["EditorExePath"] = "可执行文件路径",
		["EditorBrowse"] = "浏览",
		["RunStatusRunning"] = "运行中",
		["RunStatusStopped"] = "已停止",
		["AudioAutoSelect"] = "自动选择",
		["StatusInstanceAdded"] = "实例已新增",
		["StatusInstanceCloned"] = "实例已克隆",
		["StatusInstanceDeleted"] = "实例已删除",
		["StatusChangesApplied"] = "更改已应用",
		["StatusChangesDiscarded"] = "已放弃更改",
		["StatusInstanceStarted"] = "实例已启动",
		["StatusInstanceStopped"] = "实例已停止",
		["StatusOpenWebUiRequested"] = "已请求打开 Web UI",
		["StatusThemeChangedFmt"] = "主题已切换为：{0}",
		["StatusAllInstancesStarted"] = "全部实例已启动",
		["StatusAllInstancesStopped"] = "全部实例已停止"
	};

	private static readonly Dictionary<string, string> Ja = new(StringComparer.OrdinalIgnoreCase)
	{
		["AppName"] = "Helios - Sunshine マルチインスタンスマネージャー",
		["ThemeQuickSwitch"] = "テーマ",
		["ThemeLight"] = "ライト",
		["ThemeDark"] = "ダーク",
		["Settings"] = "設定",
		["OpenSettings"] = "設定",
		["TrayShowMain"] = "メイン画面を表示",
		["TrayInstances"] = "インスタンス",
		["TrayRestart"] = "マネージャーを再起動",
		["TrayExit"] = "終了",
		["TrayEnabled"] = "有効",
		["TrayDisabled"] = "無効",
		["StatusInstanceEnabled"] = "インスタンスを有効にしました。",
		["StatusInstanceDisabled"] = "インスタンスを無効にしました。",
		["Language"] = "言語",
		["ProductBranch"] = "製品ブランチ",
		["ProductBranchHint"] = "インストール/更新するブランチを選択",
		["ProductTargetFolder"] = "ターゲットフォルダー",
		["ProductTargetFolderHint"] = "このブランチで使用するインストール先フォルダー",
		["InstallerPathWarningTitle"] = "インストール先の注意",
		["InstallerPathWarningMessageFmt"] = "このインストーラーは対話モードで起動します。\n\n競合を避けるため、Sunshine/Apollo と同じインストール先を使用しないでください。\n手動で別フォルダーを指定してください（例）：\n{0}",
		["InstallerStarted"] = "インストーラーを起動しました。ウィザードに従って完了してください…",
		["InstallerStartedManualPathFmt"] = "インストーラーを起動しました（このインストーラーは自動パス指定に対応していません。手動で次のパスを指定してください：{0}）",
		["LanguageHint"] = "即時反映されます",
		["GroupVibeshine"] = "Sunshine",
		["GroupAutoStart"] = "自動起動",
		["GroupVolume"] = "音量同期",
		["GroupDisplay"] = "表示",
		["GroupService"] = "サービス",
		["GroupBasic"] = "基本",
		["GroupAudio"] = "音声",
		["GroupAdvanced"] = "詳細",
		["StatusBusy"] = "処理中...",
		["CheckUpdate"] = "更新を確認",
		["DownloadInstall"] = "ダウンロードしてインストール",
		["DownloadUpdate"] = "ダウンロードして更新",
		["Refresh"] = "更新",
		["DisableService"] = "サービスを無効化",
		["ServiceNotInstalled"] = "サービスがインストールされていません",
		["AutoStartTitle"] = "自動起動",
		["AutoStartDesc"] = "サインイン後にトレイアプリを起動（サービスは起動時に開始）",
		["VolumeTitle"] = "システム音量を同期",
		["VolumeDesc"] = "既定出力の音量を各インスタンスに同期",
		["DisplayRestartTitle"] = "表示変更時にインスタンスを再起動",
		["DisplayRestartDesc"] = "モニター構成・解像度変更に対応",
		["DisplayRemoveTitle"] = "切断時に仮想ディスプレイを削除",
		["DisplayRemoveDesc"] = "クライアント切断時に仮想ディスプレイを削除",
		["VibeshineDesc"] = "Sunshine のインストールと更新を管理",
		["InstalledLabel"] = "インストール済み",
		["NotInstalled"] = "未インストール",
		["BetaHint"] = "更新確認時にプレリリース版を含める",
		["AutoStartInfo"] = "タスクスケジューラでサインイン後にトレイアプリを起動（管理サービスは起動時に開始）",
		["VolumeInfo"] = "システム音量の変更を同期",
		["ServiceInfo"] = "Sunshine は既定で SunshineService（SYSTEM 権限で自動起動）をインストールします。サービスと本マネージャーの複数インスタンスを同時に動かすと競合する可能性があります。初回利用前に SunshineService を無効化することを推奨します。",
		["ServiceReminderHint"] = "この項目は注意喚起のみです。マネージャー管理インスタンスとの競合を避けるため、SunshineService と ApolloService の両方を無効化してください。",
		["ServiceCardName"] = "Sunshine サービス",
		["IncludeBeta"] = "プレリリースを含める",
		["UpdateNoRelease"] = "利用可能なリリース情報がありません",
		["UpdateNotInstalledFmt"] = "未インストール、最新: {0}",
		["UpdateAvailableFmt"] = "更新あり: {0}（インストール済み: {1}）",
		["UpdateLatestFmt"] = "最新です: {0}",
		["ServiceStatusNotInstalled"] = "未インストール",
		["ServiceStatusRunning"] = "実行中",
		["ServiceStatusStopped"] = "停止",
		["ServiceStatusStarting"] = "起動中",
		["ServiceStatusStopping"] = "停止中",
		["ServiceStatusUnknown"] = "不明",
		["ServiceStartAuto"] = "（自動）",
		["ServiceStartManual"] = "（手動）",
		["ServiceStartDisabled"] = "（無効）",
		["ListAdd"] = "追加",
		["ListClone"] = "複製",
		["ListDelete"] = "削除",
		["TipAdd"] = "インスタンスを追加",
		["TipClone"] = "インスタンスを複製",
		["TipDelete"] = "インスタンスを削除",
		["EditorSelectPrompt"] = "インスタンスを選択してください",
		["EditorApply"] = "適用",
		["EditorDiscard"] = "破棄",
		["EditorStart"] = "開始",
		["EditorStop"] = "停止",
		["EditorOpenWebUi"] = "Web UI を開く",
		["StartAll"] = "すべて開始",
		["StopAll"] = "すべて停止",
		["EditorEnable"] = "インスタンスを有効化",
		["EditorEnableHint"] = "無効なインスタンスは起動しません",
		["EditorInstanceName"] = "インスタンス名",
		["EditorInstanceNamePlaceholder"] = "名前を入力",
		["EditorPort"] = "ポート",
		["EditorPortPlaceholder"] = "48100",
		["EditorBranch"] = "ブランチ",
		["EditorBranchHint"] = "このインスタンスで使用する製品ブランチを選択",
		["EditorAudioDesc"] = "このインスタンスの音声出力デバイスを選択",
		["EditorRefreshDevices"] = "デバイスを更新",
		["EditorHeadlessTitle"] = "ヘッドレスモード",
		["EditorHeadlessDesc"] = "仮想ディスプレイ出力を作成せずに実行",
		["EditorTerminateTitle"] = "一時停止時に終了",
		["EditorTerminateDesc"] = "ストリーミング一時停止時にプロセスを停止",
		["EditorExtraArgs"] = "追加引数",
		["EditorExtraArgsPlaceholder"] = "任意のコマンドライン引数",
		["EditorExePath"] = "実行ファイルパス",
		["EditorBrowse"] = "参照",
		["RunStatusRunning"] = "実行中",
		["RunStatusStopped"] = "停止",
		["AudioAutoSelect"] = "自動選択",
		["StatusInstanceAdded"] = "インスタンスを追加しました",
		["StatusInstanceCloned"] = "インスタンスを複製しました",
		["StatusInstanceDeleted"] = "インスタンスを削除しました",
		["StatusChangesApplied"] = "変更を適用しました",
		["StatusChangesDiscarded"] = "変更を破棄しました",
		["StatusInstanceStarted"] = "インスタンスを開始しました",
		["StatusInstanceStopped"] = "インスタンスを停止しました",
		["StatusOpenWebUiRequested"] = "Web UI を開く要求を送信しました",
		["StatusThemeChangedFmt"] = "テーマを {0} に切り替えました",
		["StatusAllInstancesStarted"] = "すべてのインスタンスを開始しました",
		["StatusAllInstancesStopped"] = "すべてのインスタンスを停止しました"
	};

	private static string _currentLanguageCode = "system";

	public static event Action? LanguageChanged;

	public static string CurrentLanguageCode => _currentLanguageCode;

	public static IReadOnlyList<LanguageOption> GetLanguageOptions() =>
	[
		new("system", "Follow System"),
		new("en-US", "English"),
		new("zh-TW", "繁體中文"),
		new("zh-CN", "简体中文"),
		new("ja-JP", "日本語")
	];

	public static void Apply(string? code)
	{
		_currentLanguageCode = string.IsNullOrWhiteSpace(code) ? "system" : code;
		var cultureCode = ResolveEffectiveCultureCode(_currentLanguageCode);
		var culture = new CultureInfo(cultureCode);
		CultureInfo.DefaultThreadCurrentCulture = culture;
		CultureInfo.DefaultThreadCurrentUICulture = culture;
		Thread.CurrentThread.CurrentCulture = culture;
		Thread.CurrentThread.CurrentUICulture = culture;
		LanguageChanged?.Invoke();
	}

	public static string T(string key)
	{
		var table = ResolveTable(ResolveEffectiveCultureCode(_currentLanguageCode));
		if (table.TryGetValue(key, out var value))
		{
			return value;
		}

		if (En.TryGetValue(key, out value))
		{
			return value;
		}

		return key;
	}

	public static string ResolveEffectiveCultureCode(string? code)
	{
		if (string.IsNullOrWhiteSpace(code) || string.Equals(code, "system", StringComparison.OrdinalIgnoreCase))
		{
			return SystemCultureCode;
		}

		return code;
	}

	private static IReadOnlyDictionary<string, string> ResolveTable(string code)
	{
		if (code.StartsWith("zh-TW", StringComparison.OrdinalIgnoreCase) ||
			code.StartsWith("zh-HK", StringComparison.OrdinalIgnoreCase))
		{
			return ZhTw;
		}

		if (code.StartsWith("zh-CN", StringComparison.OrdinalIgnoreCase) ||
			code.StartsWith("zh-SG", StringComparison.OrdinalIgnoreCase))
		{
			return ZhCn;
		}

		if (code.StartsWith("ja", StringComparison.OrdinalIgnoreCase))
		{
			return Ja;
		}

		return En;
	}
}
